#!/bin/python

import os, sys

## Directories being used
LOCAL_DIR = os.getcwd()
SCR_DIR = "" 

## Cell-specific effects methods used here
METHODS = ["celldmc", "tca", "omicwas"]

rule all:
    input:
        SCR_DIR + "/" + "results/ewas/ewaff-res.tsv",
        expand(SCR_DIR + "/" + "results/ewas/{method}-res.RData", method = METHODS),
        LOCAL_DIR + "/" + "report/cs-ewas-report.html"

## Generate SVs that can be used as covariates in the EWAS
rule gen_svs:
    input:
        script = LOCAL_DIR + "/" + "scripts/gen-svs.R", 
        phen = SCR_DIR + "/" + "../data-extraction-and-qc/data/ad-data-cleaned.tsv",
        meth = SCR_DIR + "/" + "../data-extraction-and-qc/data/clean-meth.RData",
    output:
        svs = SCR_DIR + "/" + "data/svs/ad-svs.tsv",
        removed_svs = SCR_DIR + "/" + "data/svs/ad-removed-svs.RData",
    shell:
        """echo $HOSTNAME; Rscript {input.script} \
                                        '{input.phen}' \
                                        '{input.meth}' \
                                        '{output.svs}' \
                                        '{output.removed_svs}' """

## Run the "conventional" EWAS adjusting for cell counts
rule conv_ewas:
    input:
        script = LOCAL_DIR + "/" + "scripts/conventional-ewas.R", 
        phen = SCR_DIR + "/" + "../data-extraction-and-qc/data/ad-data-cleaned.tsv",
        meth = SCR_DIR + "/" + "../data-extraction-and-qc/data/clean-meth.RData",
        svs = SCR_DIR + "/" + "data/svs/ad-svs.tsv",
    output: 
        SCR_DIR + "/" + "results/ewas/ewaff-res.tsv"
    shell:
        """echo $HOSTNAME; Rscript {input.script} \
                                        '{input.phen}' \
                                        '{input.meth}' \
                                        '{input.svs}' \
                                        '{output}' """   

## Run the cell-specific EWAS
rule cs_ewas:
    input:
        script = LOCAL_DIR + "/" + "scripts/cse-ewas.R", 
        phen = SCR_DIR + "/" + "../data-extraction-and-qc/data/ad-data-cleaned.tsv",
        meth = SCR_DIR + "/" + "../data-extraction-and-qc/data/clean-meth.RData",
        svs = SCR_DIR + "/" + "data/svs/ad-svs.tsv",
    output: 
        expand(SCR_DIR + "/" + "results/ewas/{method}-res.RData", method = ["celldmc", "tca"])
    shell:
        """echo $HOSTNAME; bash {input.script} \
                                        '{input.phen}' \
                                        '{input.meth}' \
                                        '{input.svs}' \
                                        '{output}' """   

## Extract hits from the cell-specific EWAS
rule extract_hits:
    input:
        script = LOCAL_DIR + "/" + "scripts/extract-cse-hits.R", 
        celldmc = SCR_DIR + "/" + "results/ewas/celldmc.RData", 
        tca = SCR_DIR + "/" + "results/ewas/tca.RData", 
    output: 
        SCR_DIR + "/" + "results/celldmc-tca-hits.RData"
    shell:
        """echo $HOSTNAME; Rscript {input.script} \
                                        '{input.celldmc}' \
                                        '{input.tca}' \
                                        '{output}' """   

## Run omicWAS on the hits from CellDMC + TCA
rule omicwas:
    input:
        script = LOCAL_DIR + "/" + "scripts/omicwas-ewas.R",
        phen = SCR_DIR + "/" + "../data-extraction-and-qc/data/ad-data-cleaned.tsv",
        meth = SCR_DIR + "/" + "../data-extraction-and-qc/data/clean-meth.RData",
        svs = SCR_DIR + "/" + "data/svs/ad-svs.tsv",
        hits = SCR_DIR + "/" + "results/celldmc-tca-hits.RData",
    output:
        SCR_DIR + "/" + "results/ewas/omicwas-res.RData"
    shell:
        """echo $HOSTNAME; Rscript {input.script} \
                                        '{input.phen}' \
                                        '{input.meth}' \
                                        '{input.svs}' \
                                        '{input.hits}' \
                                        '{output}' """

## Summarise the results
rule summ_res:
    input:
        script = LOCAL_DIR + "/" + "scripts/omicwas-ewas.R",
        celldmc = SCR_DIR + "/" + "results/ewas/celldmc.RData", 
        tca = SCR_DIR + "/" + "results/ewas/tca.RData", 
        omicwas = SCR_DIR + "/" + "results/ewas/omicwas-res.RData",
        hits = SCR_DIR + "/" + "results/celldmc-tca-hits.RData",
        ewaff = SCR_DIR + "/" + "results/ewas/ewaff-res.tsv",        
    output:
        man = SCR_DIR + "/" + "results/celldmc-tca-manhattans.png",
        qq = SCR_DIR + "/" + "results/celldmc-tca-qqs.png",
        summ = SCR_DIR + "/" + "results/summary-of-results.RData"
    shell:
        """echo $HOSTNAME; Rscript {input.script} \
                                        '{input.celldmc}' \
                                        '{input.tca}' \
                                        '{input.omicwas}' \
                                        '{input.hits}' \
                                        '{input.ewaff}' \
                                        '{output.man}' \
                                        '{output.qq}' \
                                        '{output.summ}' """

## Generate report                                        
rule cse_report:
    input:
        man = SCR_DIR + "/" + "results/celldmc-tca-manhattans.png",
        qq = SCR_DIR + "/" + "results/celldmc-tca-qqs.png",
        summ = SCR_DIR + "/" + "results/summary-of-results.RData",
        report = LOCAL_DIR + "/" + "report/cs-ewas-report.Rmd"
    output:
        LOCAL_DIR + "/" + "report/cs-ewas-report.html"
    shell:
        """echo $HOSTNAME; \
                Rscript -e \"rmarkdown::render('{input.report}',
                                               output_format='all', 
                                               params = list(man = '{input.man}', 
                                                             qq = '{input.qq}', 
                                                             summ = '{input.summ}'))\" """

